name: mvn verify

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java: [ 17, 21, 23, 24-ea ]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: 'maven'

      - name: Download Maven Wrapper
        run: mvn wrapper:wrapper "-Dmaven=3.9.9"

      - name: Build with Maven
        run: ./mvnw -B -V -e "-Dstyle.color=always" verify